<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\Component\Utility\Html;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function soccerbet_toolbar() {
  // First, build an array of all example modules and their routes.
  // We resort to this hard-coded way so as not to muck up each example.
  $soccerbet_modules = _soccerbet_toolbar_routes();

  // Build a list of links for the menu.
  $links = [];
  foreach ($soccerbet_modules as $module => $route) {

    // Check if module is installed or not.
    if (\Drupal::moduleHandler()->moduleExists($module)) {

      // Get the module info (title, description) from Drupal.
      $info = \Drupal::service('extension.list.module')->getExtensionInfo($module);

      // If there's no info, the example isn't enabled, so don't display it.
      if (!empty($info)) {
        $links[$module] = [
          'title' => Html::escape($info['name']),
          'url' => Url::fromRoute($route),
          'attributes' => [
            'class' => [Html::getClass($module)],
            'title' => Html::escape($info['description']),
          ],
        ];
      }
    }
  }

  // Create the examples toolbar render array.
  $items['soccerbet'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Soccerbet'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => [
        'title' => t('Soccerbet'),
        'class' => ['toolbar-icon', 'toolbar-icon-soccerbet'],
      ],
    ],
    'tray' => [
      '#heading' => t('Soccerbet'),
      'shortcuts' => [
        '#theme' => 'links__toolbar_soccerbet',
        '#links' => $links,
        '#attributes' => [
          'class' => ['toolbar-menu'],
        ],
      ],
    ],
    '#weight' => 99,
    '#attached' => [
      'library' => [
        'soccerbet/soccerbet-icons',
      ],
    ],
  ];

  return $items;
}

/**
 * Get a list of toolbar links to provide.
 *
 * We've factored this list into a function so that we can use it to test
 * toolbar routes.
 *
 * This function is for internal use.
 *
 * @return string[]
 *   Keyed array of toolbar routes. Keys are the module name which supplies the
 *   route.
 */
function _soccerbet_toolbar_routes() {
  return [
    'soccerbet_tournament' => 'entity.soccerbet_tournament.collection',
    'soccerbet_team' => 'entity.soccerbet_team.collection',
  ];
}

/**
 * Implements hook_theme().
 */
function soccerbet_theme($existing, $type, $theme, $path) {
  return [
    'tournament' => [
      'path' => $path . '/templates',
      'template' => 'tournament',
      'render element' => 'elements',
    ],
  ];

  /*return array(
    'tournament' => array(
      'template' => 'tournament',
      'variables' => array(
        'name' => NULL,
        'start_date' => NULL,
        'end_date' => NULL,
        'soccerbet_tournament_tables' => NULL,
      )
    ),
    'soccerbet_tournament_tables' => array(
      'template' => 'tournament_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_tournament_table' => array(
      'template' => 'tournament_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),

        'soccerbet_tournamentgroup' => array(
    'template' => 'soccerbet_tournamentgroup',
    'variables' => array(
      'name' => NULL,
      'soccerbet_tournamentgroup_tables' => NULL,
    ),
  ),
    'soccerbet_tournamentgroup_tables' => array(
    'template' => 'tournamentgroup_tables',
    'variables' => array(
      'title' => NULL,
      'tables' => NULL,
    ),
  ),
    'soccerbet_tournamentgroup_table' => array(
    'template' => 'tournamentgroup_table',
    'variables' => array(
      'group_name' => NULL,
      'table' => NULL,
    ),
  ),

    'soccerbet_game' => array(
      'template' => 'soccerbet_game',
      'variables' => array(
        'game_location' => NULL,
        'start_time' => NULL,
        'score_first_team' => NULL,
        'score_second_team' => NULL,
        'KO_game' => NULL,
        'group_game' => NULL,
        'soccerbet_game_tables' => NULL,
      ),
    ),
    'soccerbet_game_tables' => array(
      'template' => 'game_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_game_table' => array(
      'template' => 'game_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),
    'soccerbet_usergroup' => array(
      'template' => 'soccerbet_usergroup',
      'variables' => array(
        'soccerbet_usergroup_tables' => NULL,
      )
    ),
    'soccerbet_usergroup_tables' => array(
      'template' => 'usergroup_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_usergroup_table' => array(
      'template' => 'usergroup_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),
    'soccerbet_usergroup_games' => array(
      'template' => 'usergroup_games',
      'variables' => array(
        'table' => NULL,
      ),
    ),
    'soccerbet_team' => array(
      'template' => 'soccerbet_team',
      'variables' => array(
        'team_name' => NULL,
        'soccerbet_team_tables' => NULL,
      )
    ),
    'soccerbet_team_tables' => array(
      'template' => 'team_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_team_table' => array(
      'template' => 'team_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),
    'soccerbet_team_games' => array(
      'template' => 'team_games',
      'variables' => array(
        'table' => NULL,
      ),
    ),
    'soccerbet_tip' => array(
      'template' => 'soccerbet_tip',
      'variables' => array(
        'tip_team_A' => NULL,
        'tip_team_B' => NULL,
        'soccerbet_tip_tables' => NULL,
      )
    ),
    'soccerbet_tip_tables' => array(
      'template' => 'tip_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_tip_table' => array(
      'template' => 'tip_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),
    'soccerbet_tip_games' => array(
      'template' => 'tip_games',
      'variables' => array(
        'table' => NULL,
      )
    ),
        'soccerbet_participant' => array(
    'template' => 'soccerbet_participant',
    'variables' => array(
      'soccerbet_participant_tables' => NULL,
    )
  ),
    'soccerbet_participant_tables' => array(
    'template' => 'participant_tables',
    'variables' => array(
      'title' => NULL,
      'tables' => NULL,
    ),
  ),
    'soccerbet_participant_table' => array(
    'template' => 'participant_table',
    'variables' => array(
      'group_name' => NULL,
      'table' => NULL,
    ),
  ),
    'soccerbet_participant_games' => array(
    'template' => 'participant_games',
    'variables' => array(
      'table' => NULL,
    )
  ),
    'soccerbet_participant_group' => array(
      'template' => 'soccerbet_participant_group',
      'variables' => array(
        'soccerbet_participant_group_tables' => NULL,
      )
    ),
    'soccerbet_participant_group_tables' => array(
      'template' => 'soccerbet_participant_group_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_participant_group_table' => array(
      'template' => 'soccerbet_participant_group_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),
    'soccerbet_participant_group_games' => array(
      'template' => 'soccerbet_participant_group_games',
      'variables' => array(
        'table' => NULL,
      )
    ),
    'soccerbet_tournament_group_team' => array(
      'template' => 'soccerbet_tournament_group_team',
      'variables' => array(
        'soccerbet_tournament_group_team_tables' => NULL,
      )
    ),
    'soccerbet_tournament_group_team_tables' => array(
      'template' => 'soccerbet_tournament_group_team_tables',
      'variables' => array(
        'title' => NULL,
        'tables' => NULL,
      ),
    ),
    'soccerbet_tournament_group_team_table' => array(
      'template' => 'soccerbet_tournament_group_team_table',
      'variables' => array(
        'group_name' => NULL,
        'table' => NULL,
      ),
    ),
    'soccerbet_tournament_group_team_games' => array(
      'template' => 'soccerbet_tournament_group_team_games',
      'variables' => array(
        'table' => NULL,
      )
    )
  );*/
}

/**
 * Prepares variables for the tournament template.
 *
 * Default template: tournament.html.twig
 *
 * @param array $variables
 *   - elements: An array of elements to display in view mode.
 *   - tournament: The group object.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 */
function template_preprocess_tournament(&$variables) {
  kint($variables['elements']['#tournament']);
}