<?php

/**
 * @file
 * Provides a soccerbet team entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function soccerbet_team_theme() {
  return [
    'soccerbet_team' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for soccerbet team templates.
 *
 * Default template: soccerbet-team.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the soccerbet team information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_soccerbet_team(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
